server:
  port: 8080

spring:
  application:
    name: gateway-service  #应用名称
  cloud:
    nacos:
      discovery:
        namespace: 678a3875-d937-4927-96c8-77fd21acc297
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true   #开启网关服务
          lower-case-service-id: true
      routes: # 网关服务路由配置
        - id: user-service   # 服务id
          order: 1      #优先级
          predicates: #规则定义
            - Path=/users/**
          uri: lb://user-service   #服务url
          filters:
            - StripPrefix=2
        - id: content-service
          rder: 1
          predicates:
            - Path=/shares/**
          uri: lb://content-service
#        - id: content-service
#          uri: http://localhost:8082
#          order: 1
#          predicates:
#            - Path=/shares/**
        - id: advertice-service
          order: 1
          predicates:
            - Path=/advertisement/**
          uri: lb://advertice-service
          filters:
            - StripPrefix=2
        - id: notice-service
          order: 1
          predicates:
            - Path=/notices/**
          uri: lb://notice-service
          filters:
            - StripPrefix=2

